title: Your awesome title
date: 2021-12-17 
author: Victor 
email: your-email@domain.com
description: > # this means to ignore newlines until "Allen:" 
show_excerpts: true # set to false to remove excerpts on the homepage 
theme: minima 

