title: NiIdeaaaa
date: 2021-12-17
author: MeQuieroMatar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  No se que haceeeer

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
