title: En als ik, in die leegte ben 
email: your-email@domain.com
author: Victor 
description: > # "Allen" 
date: 2021-12-17 
show_excerpts: true # set to false to remove excerpts on the homepage 
theme: minima 

